version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8080:8080"
      - "2345:2345" # 暴露 Delve 调试端口
    command: ["dlv", "debug", "--headless", "--listen=:2345", "--api-version=2", "--accept-multiclient"]
